# -*- coding: utf-8 -*-
"""WebScrapping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1crl5gA4OO7mX7VVIhOM1jF9q6TkPVLOq
"""

import requests
from bs4 import BeautifulSoup
import csv
import pandas as pd
import os

def scrape_jobs(url,excel_file='job_list.xlsx'):

  html_text=requests.get(url).text
  soup=BeautifulSoup(html_text,'lxml')
  jobs = soup.find_all('li',class_='clearfix job-bx wht-shd-bx')

  job_list=[]

  for job in jobs:
    company_name=job.find('h3',class_='joblist-comp-name').text.replace(' ','')
    skills=job.find('span',class_='srp-skills').text.replace(' ','')
    location_li = job.find('i', class_='material-icons', text='location_on').find_parent('li')
    location = location_li.find('span').text.replace(' ','')    # Extract the location information from the <span> tag
    more_info=job.header.h2.a['href']
    job_role =job.header.h2.a.text.replace(' ','')

    job_list.append({
        "Company Name ": company_name,
        "Job Role":job_role,
        "Skills Required ": skills,
        "Location ": location,
        "More Info ": more_info
    })

  new_data_df=pd.DataFrame(job_list)

  if os.path.exists(excel_file):
    existing_data_df = pd.read_excel(excel_file)
    combined_data_df = pd.concat([existing_data_df,new_data_df],ignore_index=True)
  else:
    combined_data_df = new_data_df
  combined_data_df.to_excel(excel_file,index=False)
  print(f"Data Added to the {excel_file}")

url1 = "https://www.timesjobs.com/candidate/job-search.html?searchType=personalizedSearch&from=submit&searchTextSrc=ft&searchTextText=&txtKeywords=java+and+python&txtLocation="
scrape_jobs(url1)

url2="https://www.timesjobs.com/candidate/job-search.html?from=submit&luceneResultSize=25&txtKeywords=java%20and%20python&postWeek=60&searchType=personalizedSearch&actualTxtKeywords=java%20and%20python&searchBy=0&rdoOperator=OR&pDate=I&sequence=3&startPage=1"
data = scrape_jobs(url2)

url3="https://www.timesjobs.com/candidate/job-search.html?from=submit&luceneResultSize=25&txtKeywords=java%20and%20python&postWeek=60&searchType=personalizedSearch&actualTxtKeywords=java%20and%20python&searchBy=0&rdoOperator=OR&pDate=I&sequence=4&startPage=1"
scrape_jobs(url3)

url4="https://www.timesjobs.com/candidate/job-search.html?from=submit&luceneResultSize=25&txtKeywords=java%20and%20python&postWeek=60&searchType=personalizedSearch&actualTxtKeywords=java%20and%20python&searchBy=0&rdoOperator=OR&pDate=I&sequence=5&startPage=1"
scrape_jobs(url4)

url5="https://www.timesjobs.com/candidate/job-search.html?from=submit&luceneResultSize=25&txtKeywords=java%20and%20python&postWeek=60&searchType=personalizedSearch&actualTxtKeywords=java%20and%20python&searchBy=0&rdoOperator=OR&pDate=I&sequence=6&startPage=1"
scrape_jobs(url5)

url6="https://www.timesjobs.com/candidate/job-search.html?from=submit&luceneResultSize=25&txtKeywords=java%20and%20python&postWeek=60&searchType=personalizedSearch&actualTxtKeywords=java%20and%20python&searchBy=0&rdoOperator=OR&pDate=I&sequence=7&startPage=1"
scrape_jobs(url6)

url7="https://www.timesjobs.com/candidate/job-search.html?from=submit&luceneResultSize=25&txtKeywords=java%20and%20python&postWeek=60&searchType=personalizedSearch&actualTxtKeywords=java%20and%20python&searchBy=0&rdoOperator=OR&pDate=I&sequence=8&startPage=1"
scrape_jobs(url7)

url8="https://www.timesjobs.com/candidate/job-search.html?from=submit&luceneResultSize=25&txtKeywords=java%20and%20python&postWeek=60&searchType=personalizedSearch&actualTxtKeywords=java%20and%20python&searchBy=0&rdoOperator=OR&pDate=I&sequence=9&startPage=1"
scrape_jobs(url8)

url9="https://www.timesjobs.com/candidate/job-search.html?from=submit&luceneResultSize=25&txtKeywords=java%20and%20python&postWeek=60&searchType=personalizedSearch&actualTxtKeywords=java%20and%20python&searchBy=0&rdoOperator=OR&pDate=I&sequence=10&startPage=1"
scrape_jobs(url9)

url10="https://www.timesjobs.com/candidate/job-search.html?from=submit&luceneResultSize=25&txtKeywords=java%20and%20python&postWeek=60&searchType=personalizedSearch&actualTxtKeywords=java%20and%20python&searchBy=0&rdoOperator=OR&pDate=I&sequence=11&startPage=11"
scrape_jobs(url10)

url="https://www.timesjobs.com/candidate/job-search.html?from=submit&luceneResultSize=25&txtKeywords=java%20and%20python&postWeek=60&searchType=personalizedSearch&actualTxtKeywords=java%20and%20python&searchBy=0&rdoOperator=OR&pDate=I&sequence=12&startPage=11"
scrape_jobs(url)

url="https://www.timesjobs.com/candidate/job-search.html?from=submit&luceneResultSize=25&txtKeywords=java%20and%20python&postWeek=60&searchType=personalizedSearch&actualTxtKeywords=java%20and%20python&searchBy=0&rdoOperator=OR&pDate=I&sequence=13&startPage=11"
scrape_jobs(url)

url="https://www.timesjobs.com/candidate/job-search.html?from=submit&luceneResultSize=25&txtKeywords=java%20and%20python&postWeek=60&searchType=personalizedSearch&actualTxtKeywords=java%20and%20python&searchBy=0&rdoOperator=OR&pDate=I&sequence=14&startPage=11"
scrape_jobs(url)

url="https://www.timesjobs.com/candidate/job-search.html?from=submit&luceneResultSize=25&txtKeywords=java%20and%20python&postWeek=60&searchType=personalizedSearch&actualTxtKeywords=java%20and%20python&searchBy=0&rdoOperator=OR&pDate=I&sequence=16&startPage=11"
scrape_jobs(url)

url="https://www.timesjobs.com/candidate/job-search.html?from=submit&luceneResultSize=25&txtKeywords=java%20and%20python&postWeek=60&searchType=personalizedSearch&actualTxtKeywords=java%20and%20python&searchBy=0&rdoOperator=OR&pDate=I&sequence=17&startPage=11"
scrape_jobs(url)

url="https://www.timesjobs.com/candidate/job-search.html?from=submit&luceneResultSize=25&txtKeywords=java%20and%20python&postWeek=60&searchType=personalizedSearch&actualTxtKeywords=java%20and%20python&searchBy=0&rdoOperator=OR&pDate=I&sequence=18&startPage=11"
scrape_jobs(url)

url="https://www.timesjobs.com/candidate/job-search.html?from=submit&luceneResultSize=25&txtKeywords=java%20and%20python&postWeek=60&searchType=personalizedSearch&actualTxtKeywords=java%20and%20python&searchBy=0&rdoOperator=OR&pDate=I&sequence=19&startPage=11"
scrape_jobs(url)

